### ISSUE TITLE
How to use your plugin to upload file?

### ISSUE THREAD

**Issue by HoaiDang** [lukaszlenart/struts2-gea-plugin#1]
I used to use struts2-gae-0.1.jar for my app. Now I would like to use maven and there is no repo for that lib. Then I came across your plugin. But I failed to figure out how to use your plugin for uploading file.

My current attempt:
1. Use <s:file name="file"> in jsp file
2. Have file, filenFileName, fileContentType in action class
But the file's content after upload is strange: GaeUploadedFile{name='test.csv'}

Can you help guide me how to use your plugin for file upload?

**Comment by lukaszlenart** [comment]
Everything is ok, `GaeUploadedFile` has [toString](https://github.com/lukaszlenart/struts2-gea-plugin/blob/master/src/main/java/com/gruuf/struts2/gae/dispatcher/multipart/GaeUploadedFile.java#L46-L50) re-defined.

call `file. getContent()` to get the content as `byte[]`

**Comment by HoaiDang** [comment]
I have the three fields (3 string fields) to hold uploaded file content:
	private String file;
	private String fileContentType;
	private String fileFileName;

The file content mapped by struts plugin is held in "file"" with value as the string returned by GaeUploadedFile's toString() method. Should I change to the following?

        private GaeUploadedFile file;
	private String fileContentType;
	private String fileFileName;

**Comment by lukaszlenart** [comment]
`private UploadedFile file;` or `private File file;` - the first is a proper approach on GAE as the `File` class is blacklisted.

**Comment by HoaiDang** [comment]
Thank you! It worked now.

struts2-gae-0.1.jar returns content as String, while yours returns object.

**Comment by lukaszlenart** [comment]
Nice :)
